/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dove_codec_base_Base */

#ifndef _Included_dove_codec_base_Base
#define _Included_dove_codec_base_Base
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dove_codec_base_Base
 * Method:    base64Encode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base64Encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dove_codec_base_Base
 * Method:    base64Decode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base64Decode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dove_codec_base_Base
 * Method:    base32Encode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base32Encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dove_codec_base_Base
 * Method:    base32Decode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base32Decode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dove_codec_base_Base
 * Method:    base16Encode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base16Encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dove_codec_base_Base
 * Method:    base16Decode
 * Signature: (Ljava/io/InputStream;)Ljava/io/OutputStream;
 */
JNIEXPORT jobject JNICALL Java_dove_codec_base_Base_base16Decode
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
