/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dove_codec_sha1_SHA1 */

#ifndef _Included_dove_codec_sha1_SHA1
#define _Included_dove_codec_sha1_SHA1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dove_codec_sha1_SHA1
 * Method:    sha1
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dove_codec_sha1_SHA1_sha1
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
